

server:
  port: 8093

spring:
  application:
    name: ocean-cloud-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos


