
server:
  port: 8003

spring:
  application:
    name: goods-service-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos

  sleuth:
    sampler:
      probability: 1.0
      rate: 500
  zipkin:
    base-url: http://localhost:9411

