
server:
  port: 8002

spring:
  application:
    name: shopcart-service-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos

  sleuth:
    sampler:
      probability: 1.0
      rate: 500
  zipkin:
    base-url: http://localhost:9411


logging:
  level:
    cloud:
      openfeign: debug