
server:
  port: 8001

spring:
  application:
    name: order-service-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.6:3306/test_distribution_order_tb?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: rootroot123

feign:
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 5000
seata:
  enabled: true
  application-id: order-service
  tx-service-group: test_save_order_group
  service:
    vgroup-mapping:
      test_save_order_group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:17748
      username: nacos
      password: nacos
      cluster: default
      group: DEFAULT_GROUP



