server:
  port: 8127

spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:17748
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: goods-demo-route1
          uri: lb://goods-service-demo
          order: 1
          predicates:
            - Path=/newbee-cloud/goods/**
          filters:
            - StripPrefix=1
            - GoodsId=100,1000
        - id: shopcart-demo-route
          uri: lb://shopcart-service-demo
          order: 1
          predicates:
            - Path=/shop-cart/**
          filters:
            - RedirectTo=302,https://juejin.cn

